# Generated by Django 4.2.5 on 2023-11-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_escrow_order_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='coins', max_length=15),
        ),
    ]
